spring.application.name=weather-app

api.key=1a265948486c6adaf632c6135be3b047
geocoordinates.url= http://api.openweathermap.org/geo/1.0/direct

weather.url=https://api.openweathermap.org/data/2.5/weather